services:
  xray:
    image: teddysun/xray:latest
    container_name: xray
    restart: unless-stopped
    working_dir: /app
    ports:
      - 51820:51820
      - 51820:51820/udp
    volumes:
      - ./xconfig.json:/app/xconfig.json
    entrypoint: |
      sh -c "
        xray run -c /app/xconfig.json
      "