services:
  wg:
    image: linuxserver/wireguard:latest
    container_name: wg
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=auto
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=1.1.1.1,1.0.0.1
      - INTERNAL_SUBNET=10.13.13.0
    cap_add:
      - SYS_MODULE
      - NET_ADMIN
    expose:
      - 51820/udp
    volumes:
      - ./wg0.conf:/config/wg0.conf
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      v2:
        ipv4_address: 10.13.13.2

  v2ray:
    image: v2fly/v2fly-core:latest
    container_name: v2ray
    restart: unless-stopped
    entrypoint: |
      bash -c "
        chmod +x /app/init-v2ray-server.sh &&
        /app/init-v2ray-server.sh
      "
    expose:
      - 51820/udp
    ports:
      - 60123:1433/tcp
      - 60123:1433/udp
    volumes:
      - ./v2config.json:/app/v2ray/config.json
      - ./init-v2ray-server.sh:/app/init-v2ray-server.sh
    networks:
      v2:
        ipv4_address: 10.13.13.3

networks:
  v2:
    external:
      name: v2