services:
  wg:
    image: linuxserver/wireguard:latest
    container_name: wg
    restart: unless-stopped
    working_dir: /config
    environment:
      - LOG_CONFS=false
      - PUID=1000
      - PGID=1000
      - SERVERURL=auto
      - INTERNAL_SUBNET=10.13.13.0
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=1.1.1.1,1.0.0.1
      - ALLOWEDIPS=0.0.0.0/0
      - PERSISTENTKEEPALIVE_PEERS=25
    cap_add:
      - SYS_MODULE
      - NET_ADMIN
    expose:
      - 51820/udp
    volumes:
      - ./wg/template-server.conf:/config/templates/server.conf
      - ./wg/peer1.conf:/config/peer1/peer1.conf
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      v2:
        ipv4_address: 10.13.13.2

  xray:
    image: teddysun/xray:latest
    container_name: xray
    restart: unless-stopped
    working_dir: /app
    expose:
      - 51820/udp
    ports:
      - 60123:1433/tcp
      - 60123:1433/udp
    volumes:
      - ./xray:/app/tmp
    entrypoint: |
      sh -c "
        cp /app/tmp/xconfig.json /app/xconfig.json &&
        cp /app/tmp/init-xray-server.sh /app/init-xray-server.sh &&
        chmod +x /app/init-xray-server.sh &&
        /app/init-xray-server.sh &&
        xray run -c /app/xconfig.json
      "
    networks:
      v2:
        ipv4_address: 10.13.13.3

networks:
  v2:
    name: v2
    external: true